=  Picking Numbers

== PROBLEM

Given an array of integers, find and print the maximum number of integers you
can select from the array such that the absolute difference between any two
of the chosen integers is less than or equal to 1. For example, if your
array is a = [1, 1, 2, 2, 4, 4, 5, 5, 5], you can create two subarrays meeting
the criterion: [1, 1, 2, 2] and [4, 4, 5, 5, 5]. The
maximum length subarray has 5 elements.

=== Function Description

Complete the pickingNumbers function in the editor below. It should return
an integer that represents the length of the longest array that can be
created.

pickingNumbers has the following parameter(s):

_a_: an array of integers

=== Input Format

The first line contains a single integer , the size of the array .
The second line contains  space-separated integers _a_[_i_].

=== Constraints

* 2 &lt;= n &lt;= 100
* 0 &lt; _a_[_i_ &lt; 100
* The answer will be &gt; 2.

=== Output Format

A single integer denoting the maximum number of integers you can choose from
the array such that the absolute difference between any two of the chosen
integers is .

=== Sample Input 0

...

  6
  4 6 5 3 3 1

...

=== Sample Output 0

...

  3

...

=== Explanation 0

We choose the following multiset of integers from the array: . Each pair in
the multiset has an absolute difference  (i.e.,  and ), so we print the
number of chosen integers, , as our answer.

=== Sample Input 1

...

  6
  1 2 2 3 1 2

...

=== Sample Output 1

...

  5

...

=== Explanation 1

We choose the following multiset of integers from the array: {1, 2, 2, 1, 2}. Each pair in
the multiset has an absolute difference &lt;= 1 (i.e.,|1 - 2| = 1,|1 - 1| = 0,
and |2 - 2| = 0), so we print the number of chosen integers, 5, as our
answer.
